# Generated by Django 2.0.5 on 2018-05-04 22:01

from django.db import migrations, models
import polls.cores


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contaCores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorPercent', models.IntegerField(verbose_name=polls.cores.percent)),
            ],
            bases=(models.Model, polls.cores.percent),
        ),
        migrations.CreateModel(
            name='imagemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagemImport', models.ImageField(upload_to='teste2.jpeg')),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=200)),
                ('cad_date', models.DateTimeField(verbose_name='Data de cadastro: ')),
            ],
        ),
    ]
