# Generated by Django 2.0.5 on 2018-06-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaCores', '0003_auto_20180601_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacores',
            name='foto',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
