# Generated by Django 2.0.6 on 2018-06-08 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contaCores', '0004_contacores_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacores',
            name='autor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
