# Generated by Django 2.0.6 on 2018-07-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaCores', '0005_contacores_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacores',
            name='slug',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
